# Generated by Django 4.1 on 2022-10-23 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Teams", new_name="Team",),
    ]
